//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.9
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
            "MobileHub 8fb4ea68-daf4-4727-93f4-71ff29e71201 aws-my-sample-app-android-v0.18";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-west-2");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-west-2:71c19e54-d3cb-4111-b4f9-437f98f58d47";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "1e7d4b1b0fcc41dfbc4a433fc91def10";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // Google Client ID for Web application
    public static final String GOOGLE_CLIENT_ID =
        "363608867814-m949cajitalg60q7b56947f692mjtq0e.apps.googleusercontent.com";
    // GOOGLE CLOUD MESSAGING SENDER ID
    public static final String GOOGLE_CLOUD_MESSAGING_SENDER_ID =
        "363608867814";

    // SNS PLATFORM APPLICATION ARN
    public static final String AMAZON_SNS_PLATFORM_APPLICATION_ARN =
        "arn:aws:sns:us-west-2:607139324272:app/GCM/Virtualrobe";
    public static final Regions AMAZON_SNS_REGION =
        Regions.fromName("us-west-2");
    // SNS DEFAULT TOPIC ARN
    public static final String AMAZON_SNS_DEFAULT_TOPIC_ARN =
        "arn:aws:sns:us-west-2:607139324272:dynamodb";
    // SNS PLATFORM TOPIC ARNS
    public static final String[] AMAZON_SNS_TOPIC_ARNS =
        {""};
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "";
    public static final Regions AMAZON_CONTENT_DELIVERY_S3_REGION =
       Regions.fromName("us-west-2");
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "virtualrobe-userfiles-mobilehub-1506483848";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-west-2");
    public static final Regions AMAZON_CLOUD_LOGIC_REGION =
       Regions.fromName("us-west-2");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-west-2");

    //ChatRoomDO TABLE NAME
    public static final String AMAZON_DYNAMODB_TABLENAME_CHATROOM =
            "virtualrobe-mobilehub-1506483848-ChatRoom";
    //ConversationDO TABLE NAME
    public static final String AMAZON_DYNAMODB_TABLENAME_CONVERSATION =
            "virtualrobe-mobilehub-1506483848-Conversation";
    //UserProfileDO TABLE NAME
    public static final String AMAZON_DYNAMODB_TABLENAME_USERPROFILE =
            "virtualrobe-mobilehub-1506483848-UserProfile";
}
